### PR TITLE
removed explicit web3 dependency  as it is not needed for the current

### PR DESCRIPTION
**Pull request by lakamsani**
functionality. tested with local ganache

### CODE REVIEW

**Review by sidsverma — CHANGES_REQUESTED** [review]
Thanks for the PR.
Can you:
1. Keep the package-lock.json file? https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5
2. Retain the kovan address of the smart contract so that when someone just takes in the vue file and the abi file, it just works for him on kovan.

**Comment by lakamsani** [comment]
@sidsverma  there is some [controversy](https://github.com/npm/npm/issues/20603) about that recommendation to commit `package-lock.json`. I was consulting for a large project recently where it caused problems with deployments and CI systems. As this file is re-generated on deployment Linux machines and the hashes inside it are different from the ones on Mac. What benefit do you see with keeping it? Reply back if you feel strongly about putting package-lock.json and I will do it as you are the owner of the repo.  I will be happy to revert the kovan address.

**Comment by sidsverma** [comment]
Sure, you can keep the package-lock.json file removed(also add it to .gitignore).
Also, please do revert the kovan address change.

**Comment by lakamsani** [comment]
Please check latest commit here. https://github.com/sidsverma/eth_signTypedData-example/pull/1/commits/a15f3ab26c7d5661e64bafe5444998cb68b41d06

**Review by sidsverma — APPROVED** [review]
Thanks Vamsee!

**Pull request merged**
